filetype plugin indent on

syntax on

set hidden nu ts=2 sts=2 sw=2 et ws to ttm=50 bg=dark mouse=a

set makeprg=make\ %<

let mapleader="\<Space>"
nn <leader>w :w<CR>
nn <leader>m :make<CR>

nn j gj
nn k gk

xn p pgvy

au FileType qf wincmd J

nn <C-K> :cwindow<CR>
nn <C-P> :cprev<CR>
nn <C-N> :cnext<CR>

packadd termdebug
let g:termdebug_wide=1
nnoremap <leader>d :Termdebug %:p:r<CR>

ca Hash w !cpp -dD -P -fpreprocessed \| tr -d '[:space:]' \
      \| md5sum \| cut -c-6
